name: gclone sync

on:
  schedule:
    - cron: 0 1 * * 2
  workflow_dispatch:
    inputs:
    
jobs:
  sync:
    runs-on: ubuntu-latest
    name: TD sync

    steps:
      - uses: actions/checkout@v2
      - name: gclone Install
        run: |
          wget -qO- https://api.github.com/repos/donwa/gclone/releases/latest \
          | grep browser_download_url | grep Linux_x86_64 | cut -d '"' -f 4 \
          | wget --no-verbose -i- -O- | gzip -d -c > rclone
          sudo mv rclone /usr/bin
          sudo chmod +x /usr/bin/rclone
      - name: gclone Config
        run: |
          mkdir -p ~/.config/rclone
          mkdir -p sa
          cd sa
          curl -L "${{ secrets.GCLONE_SA_DLURL }}" -o accounts.zip
          unzip -jq -o accounts.zip
          cd ..
          cat >  ~/.config/rclone/rclone.conf  << EOF
          ${{ secrets.GCLONE_CONFIG_SYNC }}
          EOF
      - name: gclone Run
        run: |
          echo "::add-mask::gclone sa file: sa/"
          echo "::add-mask::.json"
          rclone sync ${{ secrets.GCLONE_PATH_SYNC }} --drive-server-side-across-configs
